### ISSUE TITLE
Failing deployment, Vercel Payment has failed

### ISSUE THREAD

**Issue by rsmets** [ethereum-boilerplate/ethereum-nft-marketplace-template#6]
Hey guys, looks like the payment info needs to be updated for Vercel or need to figure out another deployment platform. 

https://github.com/ethereum-boilerplate/ethereum-nft-marketplace-template/commit/a7f835a94f5121434bad14db79d462e3988550ce#commitcomment-67518947

Thanks for all your hard work! 

I guess while I am here (off-topic...) what is the difference between this template project and the [boilerplate project](https://github.com/ethereum-boilerplate/ethereum-nft-marketplace-boilerplate)? Off the bat I see this template project uses the new Moralis web3ui kit, does that mean the template is the one to use moving forward?

Thanks again.

**Comment by locothedev** [comment]
@rsmets main difference is that this will revolutionize web3 coding even more but it is not supported and maintained. It is a prototype that is not meant to be used yet. Vercel was just testing purposes.
