### ISSUE TITLE
× Unhandled Rejection (TypeError): Cannot read properties of undefined (reading 'address')

### ISSUE THREAD

**Issue by Mohaimen13** [ethereum-boilerplate/ethereum-nft-marketplace-template#7]
I'm getting this error when trying to deploy project on

Unhandled Rejection (TypeError): Cannot read properties of undefined (reading 'address')
(anonymous function)
src/views/Admin/Module/contracts/Registry/useRegistry.ts:87
  84 | },
  85 | onSuccess: results => {
  86 |     (results as any).wait().then((e) => {
> 87 |         save({admin: account, uri: uri, protocol: e.logs[0].address, chain: chainId}).then(console.log).catch(console.log).then( () => {
     | ^  88 |             setCanSetProject(false)
  89 |             setLoading(false)
  90 |         })

**Comment by locothedev** [comment]
This repo is not official yet
