### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by yusufferdogan** [ethereum-boilerplate/ethereum-nft-marketplace-template#8]
![image](https://user-images.githubusercontent.com/45846424/186933420-862cc0c6-a338-48af-8d0f-6b3503bf71ac.png)

**Comment by locothedev** [comment]
Hi. This repo is not maintained yet but will be soon. But your issue looks like a React 18 thing. FCs do not have implicit children anymore in react 18. You need to specify the children type.
